### ISSUE TITLE
UART Question

### ISSUE THREAD

**Issue by halogen28372** [allexoK/Esp32-Stick-Boards-Docs#1]
Thanks for developing the board, I am looking forward to using it in my projects.  I do have a question, which pins are available to UART?  A related question is also which pins can be used for what IO in general. I have seen charts such as this for other boards. https://randomnerdtutorials.com/esp32-pinout-reference-gpios/

**Comment by allexoK** [comment]
Hello, enjoy! The only available default UART pins are TX0(GPIO1) and RX0(GPIO3). However other pins can also be used for UART using remapping technique(https://github.com/espressif/arduino-esp32/issues/2858).
I also added an updated pinout diagram with the most popular functions(ADC, SPI...), checkout README 'Pinout and dimensions'. The link that you have sent can also be used since the board uses ESP32-WROOM as a core.

**Comment by halogen28372** [comment]
Very cool thank you.
